# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-20 18:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=1000)),
                ('genre', models.CharField(max_length=20)),
                ('premiere_date', models.DateField()),
                ('session_time', models.TimeField()),
                ('film_duration', models.IntegerField()),
                ('price', models.FloatField()),
            ],
        ),
    ]
