# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-21 16:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0002_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poster',
            name='is_main',
            field=models.BooleanField(default=False),
        ),
    ]
