# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-21 16:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0003_auto_20171021_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poster',
            name='pic',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
