# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-21 20:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0006_auto_20171021_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookedplace',
            name='booking_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 21, 20, 47, 26, 51140)),
        ),
    ]
