# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-21 21:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cinema', '0007_bookedplace_booking_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookedplace',
            name='author',
        ),
        migrations.AddField(
            model_name='bookedplace',
            name='customer',
            field=models.ForeignKey(db_column='customer', default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bookedplace',
            name='booking_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
