# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-21 21:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0008_auto_20171021_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookedplace',
            name='customer',
            field=models.ForeignKey(db_column='customer', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
