# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-22 11:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0010_auto_20171021_2231'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bookedplace',
            unique_together=set([('film', 'place', 'row')]),
        ),
        migrations.AlterUniqueTogether(
            name='film',
            unique_together=set([('title', 'session_time')]),
        ),
        migrations.AlterUniqueTogether(
            name='poster',
            unique_together=set([('film', 'pic')]),
        ),
    ]
